image: python:3.9

stages:
  - security
  - code_analysis
  - other_issues

# Security analysis stage
security_scan:
  stage: security
  script:
    # Install necessary packages
    - apt-get update && apt-get install -y python3-pip python3-setuptools python3-wheel
    - pip3 install -r requirements.txt
    - pip3 install safety bandit

    # Run security analysis
    - safety check --full-report
    - bandit -r .

    #  Run Django-specific security checks
    - python3 manage.py check --deploy --fail-level=WARNING

# Code analysis stage
code_analysis:
  stage: code_analysis
  script:
    # Install necessary packages
    - apt-get update && apt-get install -y python3-pip python3-setuptools python3-wheel
    - pip3 install -r requirements.txt
    - pip3 install pylint

    # Run code analysis
    - pylint **/*.py

# Other recommended issues stage
other_issues:
  stage: other_issues
  script:
    # Install necessary packages
    - apt-get update && apt-get install -y python3-pip python3-setuptools python3-wheel
    - pip3 install -r requirements.txt
    - pip3 install flake8

    # Run flake8
    - flake8 --ignore=E501 .

    # Run Django-specific style checks
    - flake8 --max-line-length=119 --exclude=migrations,settings.py --extend-ignore=D100,D101,D102,D103,D104,D105 app_name/

