version: 2.1

orbs:
  python: circleci/python@2.1.1
  ansible: trustedshops-public/ansible@2.0.0
  codecov: codecov/codecov@3.2.4

jobs:
  build:
    docker:
      - image: circleci/python:3.7
        environment:
          DB_USER: root
          DB_NAME: circle_test
          DB_URL: localhost
          DB_PASSWORD: ''
          DB_PORT: 5432
          DB_HOST: localhost

      - image: circleci/postgres:9.6.2
        environment:
          DB_USER: root
          DB_NAME: circle_test
          DB_URL: localhost
          DB_PASSWORD: ''
          DB_PORT: 5432
          DB_HOST: localhost
    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum ".circleci/requirements.txt" }}
      - run:
          command: |
            python3 -m venv venv
            . venv/bin/activate
            python3 -m pip install --upgrade pip
            pip install -r .circleci/requirements.txt
      - run:
          name: Run tests
          command: |
            . venv/bin/activate
            python manage.py test --settings=cookiecutter.development
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results
          destination: tr1
      - persist_to_workspace:
          root: ~/project
          paths:
            - .

      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum ".circleci/requirements.txt" }}
          paths:
            - "venv"

workflows:
  build-and-deploy:
    jobs:
      - build:
          filters:
            branches:
              only: /.*/
      - build:
          filters:
            branches:
              only: release
        
