version: 2.1

orbs:
  python: circleci/python@2.1.1
  ansible: orbss/ansible@0.2.3
  codecov: codecov/codecov@3.2.4

jobs:
  build:
    docker:
      - image: circleci/python:3.9.7-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: ""
      DJANGO_SETTINGS_MODULE: config.settings.development
      MY_ENV_VAR: "my-value"
    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - run:
          name: Run tests
          command: tox

      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "venv"

workflows:
  build-and-deploy:
    jobs:
      - build:
          filters:
            branches:
              only: develop
      - build:
          filters:
            branches:
              only: release
